.TH capture 1 "March 2003"
.SH NAME
capture \- capture EAS alerts from audio
.SH SYNOPSIS
.B capture [-d
.I dir
.B ] [-l
.I log-file
.B ] [-s
.I script
.B ]
.I file
.SH DESCRIPTION
.B capture
reads audio data from
.I file
(or stdin if
.I file
is \-),
decodes any SAME (Specific Area Message Encoding) digital data,
and writes the resulting alert audio clips to disk.

The audio clips are written to disk in MP3 format.
The
.IR lame (1)
audio compressor is used to create the MP3 files.

After creating the audio clip, capture sets the
environment variables EAS_MESSAGE and EAS_MP3 and
runs the
.I script
specified in the command line.
.SH OPTIONS
.IP "-d dir"
The directory where MP3 files will be created.
.IP "-l log-file"
The log file to which EAS events will be written.
.IP "-s script"
The command to run after capturing an MP3 file.
.IP file
The file that contains audio data. If \- is specified,
read from stdin.
.SH AUTHOR
Greg Hewgill <greg@hewgill.com>
.br
http://www.hewgill.com
.SH "SEE ALSO"
.BR lame (1),
.BR streamer (1)
