.TH log 1 "March 2003"
.SH NAME
log \- write a stream to a rotating log file
.SH SYNOPSIS
.B log
.I dir
.SH DESCRIPTION
.B log
reads a stream from its stdin,
and writes the stream to a file in the specified
.IR dir .

Every hour, the current log file is closed,
a new one is opened,
and an older log file is deleted.
.SH OPTIONS
.IP dir
The directory to which the log files will be written.
.SH BUGS
There is no way to change the rotation interval (one hour),
the number of log files that are kept (3),
or the log filenames used (NWR-*.raw).
.SH AUTHOR
Greg Hewgill <greg@hewgill.com>
.br
http://www.hewgill.com
